### ISSUE TITLE
Getting intermittent "No table mappings provided"

### ISSUE THREAD

**Issue by vylor0601** [kjbartel/efbulkinsert#1]
Getting intermittent "No table mappings provided." at least once a week on my project when using BulkInsert. Below is the stack trace:

Stack Trace:    at EntityFramework.BulkInsert.Helpers.MappedDataReader`1..ctor(IEnumerable`1 enumerable, IEfBulkInsertProvider provider)
   at EntityFramework.BulkInsert.Providers.EfSqlBulkInsertProviderWithMappedDataReader.Run[T](IEnumerable`1 entities, SqlTransaction transaction)
   at EntityFramework.BulkInsert.Providers.ProviderBase`2.Run[T](IEnumerable`1 entities, IDbTransaction transaction)
   at EntityFramework.BulkInsert.Providers.ProviderBase`2.Run[T](IEnumerable`1 entities)
   at EntityFramework.BulkInsert.Extensions.BulkInsertExtension.BulkInsert[T](DbContext context, IEnumerable`1 entities, BulkInsertOptions options)
   at EntityFramework.BulkInsert.Extensions.BulkInsertExtension.BulkInsert[T](DbContext context, IEnumerable`1 entities, SqlBulkCopyOptions sqlBulkCopyOptions, Nullable`1 batchSize)
   at EntityFramework.BulkInsert.Extensions.BulkInsertExtension.BulkInsert[T](DbContext context, IEnumerable`1 entities, Nullable`1 batchSize)

**Comment by vylor0601** [comment]
`var dlAssociatesBeforeRun = adHelper.GetDLAssociates(dl.DLName)
                                .Select(x =>
                                    new TP_DLAssociatesBeforeRun
                                    {
                                        DLID = dl.ID,
                                        ADUsername = x.ADUsername,
                                        CreateDate = DateTime.Now,
                                        CreateBy = "ADUtility.CLI",
                                        UpdateDate = DateTime.Now,
                                        UpdateBy = "ADUtility.CLI"
                                    }).ToList();
                            _logger.Trace($"Detected {dlAssociatesBeforeRun.Count} for DL {dl.DLName}");
                            // ReSharper disable once InvertIf
                            if (dlAssociatesBeforeRun.Any())
                            {
                                db.BulkInsert(dlAssociatesBeforeRun);
                                db.SaveChanges();`

**Comment by vylor0601** [comment]
Below is the code I am using - using EF Database First:

![image](https://user-images.githubusercontent.com/21280061/28606490-4e9d53c0-71a5-11e7-978f-180a30caeb68.png)

**Comment by kjbartel** [comment]
Sorry I can't really help you out as I didn't write the library. I used this library a few years ago and made a couple of small changes for my needs which are included in this repo. You might want to try out the updated library which now appears to be on github: [EntityFramework-Extensions](https://github.com/zzzprojects/EntityFramework-Extensions)
